// Mocks generated by Mockito 5.4.6 from annotations
// in sptimer/test/pomodoro_timer_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:sptimer/data/enums/pomodoro_status.dart' as _i6;
import 'package:sptimer/data/enums/tones.dart' as _i5;
import 'package:sptimer/data/models/task.dart' as _i4;
import 'package:sptimer/data/services/pomodoro_sound_player.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [PomodoroSoundPlayer].
///
/// See the documentation for Mockito's code generation for more information.
class MockPomodoroSoundPlayer extends _i1.Mock
    implements _i2.PomodoroSoundPlayer {
  @override
  _i3.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> isSoundPlayerMuted(_i4.Task? task) =>
      (super.noSuchMethod(
            Invocation.method(#isSoundPlayerMuted, [task]),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> isRingerMuted() =>
      (super.noSuchMethod(
            Invocation.method(#isRingerMuted, []),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> cantPlaySound() =>
      (super.noSuchMethod(
            Invocation.method(#cantPlaySound, []),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> canVibrate() =>
      (super.noSuchMethod(
            Invocation.method(#canVibrate, []),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> vibrate() =>
      (super.noSuchMethod(
            Invocation.method(#vibrate, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setVolume(double? volume) =>
      (super.noSuchMethod(
            Invocation.method(#setVolume, [volume]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> playTone(_i5.Tones? tone, [double? volume]) =>
      (super.noSuchMethod(
            Invocation.method(#playTone, [tone, volume]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> playPomodoroSound({
    required _i4.Task? task,
    required _i6.PomodoroStatus? pomodoroStatus,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#playPomodoroSound, [], {
              #task: task,
              #pomodoroStatus: pomodoroStatus,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> readStatusAloud(_i6.PomodoroStatus? status) =>
      (super.noSuchMethod(
            Invocation.method(#readStatusAloud, [status]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
